"""
LLM base abstract class
Defines the interface standard that all LLM implementations must follow
"""

from abc import ABC, abstractmethod
from typing import Optional, Dict, Any


class BaseLLM(ABC):
    """LLM base abstract class"""
    
    def __init__(self, api_key: str, model_name: Optional[str] = None):
        """
        Initialize the LLM client
        
        Args:
            api_key: API key
            model_name: Model name, uses the default model if not specified
        """
        self.api_key = api_key
        self.model_name = model_name
        
    @abstractmethod
    def invoke(self, system_prompt: str, user_prompt: str, **kwargs) -> str:
        """
        Invoke the LLM to generate a reply
        
        Args:
            system_prompt: System prompt
            user_prompt: User input
            **kwargs: Other parameters, e.g. temperature, max_tokens, etc.
            
        Returns:
            Reply text generated by the LLM
        """
        pass
    
    @abstractmethod
    def get_default_model(self) -> str:
        """
        Get the default model name
        
        Returns:
            Default model name
        """
        pass
    
    def validate_response(self, response: str) -> str:
        """
        Validate and clean the response content
        
        Args:
            response: Raw LLM response
            
        Returns:
            Cleaned response content
        """
        if response is None:
            return ""
        return response.strip()
